### ISSUE TITLE
Post Deliverable Checklist for Sprint 01

### ISSUE THREAD

**Issue by menardj** [Gocoala/simple-chat-app#9]
Your progress so far [1.75%]
All the issues you created (and hopefully completed) for the past deliverable. [1.75%]
Anything you found was a positive from the past few weeks minimum of 2 [1.75%]
Anything you found didn't work out so well from the past few weeks [1.75%]
Ask Eric Adamski for feedback on a part of your project. minimum of 1 [1.75%]

**Comment by menardj** [comment]
# Progress
- [x] Paper Wireframes
  - [x] 404 page
  - [x] Chat (main) page
  - [x] Members List
  - [x] Notifications
    - [x] Joined
    - [x] Left
- [ ] Interactive Wireframes
  - [ ] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left
- [ ] Complete Project
  - [ ] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left

# Issues
Completed: All issues for Sprint 01.

# Positives :+1:

+ Was great to see how our wireframes ended up being similar in style
+ our design, while not developed yet seems to be headed in the same direction
+ Nicole went the extra mile to map out each part/feature we might need in development

# Improvements :star:

+ getting started the whole process was a little overwhelming/confusing
+ i could have been a little more in-depth with my wireframes
+ could maybe use a more outlined goal system for myself

# Request for Feedback :ear:

+ Maybe just some way of letting us know we're on the right track

**Comment by Gocoala** [comment]
# Progress
- [x] Paper Wireframes
- [x ] 404 page
- [x] Chat (main) page
- [x] Members List
- [x] Notifications
- [x] Joined
- [x ] Left

# Issues
Completed: #1, #2, #3, ...

# Positives :+1:

+Good exploratory options from all team members.
+It's excellent to get to see a window into an intranet environment.
+Lots of information to take in all at once. The other classes are already heavy in content. It would also be important to find out overall. How many team projects have been assigned in total for this semester. Altogether, we have 3. It's a challenge to get everyone together when everyone is super busy.

# Improvements :star:

+It would be wonderful to look at more examples of chat systems that are done well.
+What are the common problems in chat systems?  
+What are the challenges with chat systems?

# Request for Feedback :ear:

+I understand that the screens do not have to be coded together and that they are already done.
+Are we just simply working out those few individual screens that you had listed in the interactive wireframe list? I thought we had to code from screen to screen.
+How to stay on track with this project?   

Nicole

**Comment by ericadamski** [comment]
@Gocoala you have some very good points I would like to address, could you remind me of them in class? You guys are doing a great job so far!
